var searchData=
[
  ['testmethod',['testMethod',['../class_sol_a_r_1_1api_1_1solver_1_1pose_1_1_i2_dto3_d_transform_decomposer_validation.html#af1a316dd3f8ada43aaeeb878d3fd0276',1,'SolAR::api::solver::pose::I2Dto3DTransformDecomposerValidation']]],
  ['trackable',['Trackable',['../class_sol_a_r_1_1datastructure_1_1_trackable.html#a304aa9da8e2dbbff4859644c7da69c4f',1,'SolAR::datastructure::Trackable::Trackable()=default'],['../class_sol_a_r_1_1datastructure_1_1_trackable.html#a10b972b80daf83c89fe1cd391a8454a1',1,'SolAR::datastructure::Trackable::Trackable(const std::string &amp;url)']]],
  ['trackable2d',['Trackable2D',['../class_sol_a_r_1_1datastructure_1_1_trackable2_d.html#a65dfc562ff7f8882a44a36689dfeb622',1,'SolAR::datastructure::Trackable2D::Trackable2D()=default'],['../class_sol_a_r_1_1datastructure_1_1_trackable2_d.html#a025a263937080acd471bdf37634b2710',1,'SolAR::datastructure::Trackable2D::Trackable2D(const std::string &amp;url, const Sizef &amp;size)'],['../class_sol_a_r_1_1datastructure_1_1_trackable2_d.html#ad03867ebae809df1a8cd918cc57ae920',1,'SolAR::datastructure::Trackable2D::Trackable2D(const std::string &amp;url, const float &amp;width, const float &amp;height)']]],
  ['transform',['transform',['../class_sol_a_r_1_1api_1_1geom_1_1_i2_d_transform.html#a9a7f7c3e8ec17533d8ea5f5222bff6d2',1,'SolAR::api::geom::I2DTransform::transform()'],['../class_sol_a_r_1_1api_1_1geom_1_1_i3_d_transform.html#ae661722cc9d138e19ca17deacb724695',1,'SolAR::api::geom::I3DTransform::transform(const std::vector&lt; datastructure::Point3Df &gt; &amp;inputPoints, const datastructure::Transform3Df &amp;transformation, std::vector&lt; datastructure::Point3Df &gt; &amp;outputPoints)=0'],['../class_sol_a_r_1_1api_1_1geom_1_1_i3_d_transform.html#a7b8de40299c821351c245f65dc5561f8',1,'SolAR::api::geom::I3DTransform::transform(const datastructure::Transform3Df &amp;transformation, SRef&lt; api::solver::map::IMapper &gt; map)=0']]],
  ['transforminplace',['transformInPlace',['../class_sol_a_r_1_1api_1_1geom_1_1_i3_d_transform.html#a69e0af5a6bcd07483abe903b8f9da5f4',1,'SolAR::api::geom::I3DTransform']]],
  ['triangulate',['triangulate',['../class_sol_a_r_1_1api_1_1solver_1_1map_1_1_i_triangulator.html#a4d707253855d1c2edd4edc206f455a56',1,'SolAR::api::solver::map::ITriangulator::triangulate(const std::vector&lt; datastructure::Point2Df &gt; &amp;pointsView1, const std::vector&lt; datastructure::Point2Df &gt; &amp;pointView2, const std::vector&lt; datastructure::DescriptorMatch &gt; &amp;matches, const std::pair&lt; unsigned int, unsigned int &gt; &amp;working_views, const datastructure::Transform3Df &amp;poseView1, const datastructure::Transform3Df &amp;poseView2, std::vector&lt; SRef&lt; datastructure::CloudPoint &gt;&gt; &amp;pcloud)=0'],['../class_sol_a_r_1_1api_1_1solver_1_1map_1_1_i_triangulator.html#a11bebc2d35fb2d34b63093c1d03e0d1a',1,'SolAR::api::solver::map::ITriangulator::triangulate(const std::vector&lt; datastructure::Keypoint &gt; &amp;keypointsView1, const std::vector&lt; datastructure::Keypoint &gt; &amp;keypointsView2, const std::vector&lt; datastructure::DescriptorMatch &gt; &amp;matches, const std::pair&lt; unsigned int, unsigned int &gt; &amp;working_views, const datastructure::Transform3Df &amp;poseView1, const datastructure::Transform3Df &amp;poseView2, std::vector&lt; SRef&lt; datastructure::CloudPoint &gt;&gt; &amp;pcloud)=0'],['../class_sol_a_r_1_1api_1_1solver_1_1map_1_1_i_triangulator.html#a20f93319accc38a25192adf6d15a5b1b',1,'SolAR::api::solver::map::ITriangulator::triangulate(const std::vector&lt; datastructure::Keypoint &gt; &amp;keypointsView1, const std::vector&lt; datastructure::Keypoint &gt; &amp;keypointsView2, const SRef&lt; datastructure::DescriptorBuffer &gt; &amp;descriptor1, const SRef&lt; datastructure::DescriptorBuffer &gt; &amp;descriptor2, const std::vector&lt; datastructure::DescriptorMatch &gt; &amp;matches, const std::pair&lt; unsigned int, unsigned int &gt; &amp;working_views, const datastructure::Transform3Df &amp;poseView1, const datastructure::Transform3Df &amp;poseView2, std::vector&lt; SRef&lt; datastructure::CloudPoint &gt;&gt; &amp;pcloud)=0'],['../class_sol_a_r_1_1api_1_1solver_1_1map_1_1_i_triangulator.html#a6c54414951058fe75c5cf09e5dcad21b',1,'SolAR::api::solver::map::ITriangulator::triangulate(const SRef&lt; datastructure::Keyframe &gt; &amp;curKeyframe, const std::vector&lt; datastructure::DescriptorMatch &gt; &amp;matches, std::vector&lt; SRef&lt; datastructure::CloudPoint &gt;&gt; &amp;pcloud)=0']]],
  ['tryget',['tryGet',['../class_sol_a_r_1_1api_1_1sink_1_1_i_sink_pose_image.html#a7907f17772cbef7b1b3037449f7c704c',1,'SolAR::api::sink::ISinkPoseImage']]],
  ['tryupdate',['tryUpdate',['../class_sol_a_r_1_1api_1_1sink_1_1_i_sink_pose_texture_buffer.html#a2b3acf6200afd1d54634afa12ac794ba',1,'SolAR::api::sink::ISinkPoseTextureBuffer']]]
];
